features:
  arrival_time: [1]
  american: [0,1]
  delta: [0,1]
  jetblue: [0,1]
  southwest: [0,1]
  longest_stop: [1]
  num_stops: [0]
  price: [1]

true_reward: [0, 1, 0, -1, 0.5, 1, -1, 0]

human_feature_map: [0,0,0,1,1,1,1,0]
gt_feature_map: [0,1,0,1,1,1,1,0]