name: feature-preference
channels:
- pytorch
- defaults
dependencies:
- python=3.9
- pip
- ipython
- torchvision
- pip:
  - click
  - cloudpickle
  - gym>=0.18.3
  - matplotlib
  - numpy>=1.20.3
  - tqdm
  - seaborn
  - jupyterlab