features:
  texture: [[1,0,0],[0,1,0],[0,0,1]]
  color: [[1,0,0],[0,1,0],[0,0,1]]
  shape: [[1,0,0],[0,1,0],[0,0,1]]
  height: [[1,0,0],[0,1,0],[0,0,1]]
  weight: [[1,0,0],[0,1,0],[0,0,1]]
  smell: [[1,0,0],[0,1,0],[0,0,1]]

true_reward:
  texture: [0, 0, 0]
  color: [0, 0, 0]
  shape: [0, 0, 0]
  height: [0, 0, 0]
  weight: [0, 0, 0]
  smell: [1, -2, 0]

human_feature_map: [0,0,0,0,0,1]
