features:
  texture: [[1,0,0],[0,1,0],[0,0,1]]
  color: [[1,0,0],[0,1,0],[0,0,1]]
  shape: [[1,0,0],[0,1,0],[0,0,1]]
  height: [[1,0,0],[0,1,0],[0,0,1]]
  weight: [[1,0,0],[0,1,0],[0,0,1]]
  smell: [[1,0,0],[0,1,0],[0,0,1]]

true_reward:
  texture: [-2, 0, 1]
  color: [1, -1, 2]
  shape: [0, 2, -2]
  height: [1, -2, 2]
  weight: [-1, 0, 1]
  smell: [2, -1, 1]

human_feature_map: [1,1,1,1,1,1]