features:
  texture: [[1,0,0],[0,1,0],[0,0,1]]
  color: [[1,0,0],[0,1,0],[0,0,1]]
  shape: [[1,0,0],[0,1,0],[0,0,1]]
  height: [[1,0,0],[0,1,0],[0,0,1]]
  weight: [[1,0,0],[0,1,0],[0,0,1]]
  smell: [[1,0,0],[0,1,0],[0,0,1]]

true_reward:
  texture: [-2, 1, 0]
  color: [2, -1, 0]
  shape: [1, -2, 2]
  height: [0, 0, 1]
  weight: [1, 2, -1]
  smell: [0, -2, 2]